### ISSUE TITLE
Default permissions for Global moderator are not editables

### ISSUE THREAD

**Issue by Galixte** [rfdy/trader#14]
Hi,

when you activate this extension, in ACP => Permissions => Group permissions => Global moderators
The two next permissions are set on "Yes" even if it's set "no role assigned...":
```
Can leave trader feedback
Can view trader feedback
```

If i change the permissions on "NO" for them and i save, those two permissions will be back set on "Yes".

**Comment by rfdy** [comment]
Unable to replicate this issue.

**Comment by Galixte** [comment]
OK, sorry after unistall this extension, then reset permissions for Global moderator group, then re-install this extension it's fine for this issue ;).
