### ISSUE TITLE
styles/all/template/event/navbar_header_profile_list_after.html broken

### ISSUE THREAD

**Issue by rogalian** [rfdy/trader#21]
Replacement string is missing the app.php part.

/app.php/trader/view-feedback/?u=

**Comment by Galixte** [comment]
it's your PR ? https://github.com/rfdy/trader/pull/8

It doesn't fixe it ?

**Comment by rogalian** [comment]
It does fix it, I didn't know it hadn't been merged yet!

**Comment by Galixte** [comment]
yes but in waiting you can edit this file manually ;)

**Comment by Galixte** [comment]
Can be close, already merged.
