### ISSUE TITLE
No informations for some tabs

### ISSUE THREAD

**Issue by Galixte** [rfdy/trader#23]
Hi,

maybe since your lasts commits on Apr 20, 2015, on ```/trader/view-feedback/?u=3``` page (Trader Feedback for USERNAME), i don't see the informations about feedbacks on next tabs:
- From Buyers
- From Sellers
- From Trades

For others tabs it's OK:
- All Feedback Received
- Left for Others

**Comment by rfdy** [comment]
Unable to reproduce this issue.
![trader_non_bug](https://cloud.githubusercontent.com/assets/7172700/7278247/1d212aa4-e8e2-11e4-936f-a9197208f437.jpg)

**Comment by Galixte** [comment]
Since a new installation, i can’t to reproduce this issue too.
