### ISSUE TITLE
Any news ?

### ISSUE THREAD

**Issue by Galixte** [rfdy/trader#35]
Hi @rfdy,

could you take a look about this: https://www.phpbb.com/community/viewtopic.php?p=14263401#p14263401.

**Comment by Galixte** [comment]
Hi @rfdy,

bump !

**Comment by rfdy** [comment]
Hi @Galixte,

I apologize that we've been unresponsive.  Maintaining our open source extensions hasn't been very high on the priority list recently.

We appreciate the fixes from the community and will restart merging pull requests - beginning with your "All fixes" branch.

**Comment by Galixte** [comment]
Thanks, i don’t close this because all of problems are not resolved. !-)

**Comment by Leinad4Mind** [comment]
Any news rfdy?

**Comment by lawsontyler** [comment]
@Leinad4Mind There is no new news.

**Comment by Galixte** [comment]
Hi @Leinad4Mind do you think you can fix the last opened issues?
